### ISSUE TITLE
proxy tests

### ISSUE THREAD

**Issue by jonathanong** [cojs/cogent#1]
not sure what the best way to do this is. https://github.com/component/package.js/pull/5#issuecomment-30680974

**Comment by deepak1556** [comment]
is the `default.proxy` = `process.env.HTTP_PROXY || process.env.http_proxy` ? it seems to be not initialised.

**Comment by jonathanong** [comment]
oh is that a thing? i don't check for env vars right now.

**Comment by deepak1556** [comment]
cool, not necessary at the moment for writing tests.

**Comment by jonathanong** [comment]
https://github.com/cojs/cogent/pull/11
