### ISSUE TITLE
buffer tests fails first time on slower networks

### ISSUE THREAD

**Issue by deepak1556** [cojs/cogent#12]
Adding a logger in the request function shows no response is received first time but when running successive tests returns statuscode 200. Have to dig in deeper and will update the issue.

**Comment by jonathanong** [comment]
if there's a close event, it'll just pause indefinitely i think. that might be the issue. if there's a timeout then no response might be received, though it should really throw in that case.

**Comment by deepak1556** [comment]
yeah but there wasnt any timeout error thrown by the request.

**Comment by jonathanong** [comment]
not sure what to do here. reopen if you know what's going on
